const dictionaries = {
  ru: {
    appName: 'Фаҳмо AI',
    tagline: 'Из документа — в понятный план',
    navHome: 'Главная', navAnalyze: 'Новый анализ', navHistory: 'История', navSettings: 'Настройки',
    online: 'В сети', offline: 'Нет подключения',
    heroDescription: 'Загрузите объявление, поручение, записку или другой документ. Мы выделим главное и создадим понятный список действий.',
    addDocument: 'Добавить документ', tryExample: 'Попробовать на примере',
    supported: 'Фото · Изображения · PDF · Текст',
    flowShort: 'Кратко и понятно', flowShortDesc: 'Выделяем суть и убираем лишнее.',
    flowTasks: 'Что нужно сделать', flowTasksDesc: 'Превращаем информацию в конкретные шаги.',
    flowData: 'Важные данные', flowDataDesc: 'Находим даты, суммы, места и контакты.',
    flowSource: 'Источники', flowSourceDesc: 'Показываем, откуда взята информация.',
    recent: 'Последние анализы', viewAll: 'Посмотреть все',
    noHistoryTitle: 'История пока пуста', noHistoryText: 'Добавьте первый документ или запустите безопасный пример, чтобы увидеть полный сценарий.',
    stepAdd: 'Добавить', stepReview: 'Проверить страницы', stepConfigure: 'Настроить анализ',
    analyzeTitle: 'Подготовка документа', analyzeSubtitle: 'Добавьте страницы, проверьте порядок и выберите параметры результата.',
    sourceFiles: 'Файлы', sourceText: 'Текст',
    dropTitle: 'Перетащите файл сюда', dropText: 'или выберите удобный способ добавления',
    chooseFile: 'Выбрать файл', takePhoto: 'Сфотографировать', pasteImage: 'Вставить изображение', pasteText: 'Вставить текст',
    uploadHint: 'PDF, PNG, JPG, WEBP или TXT · до 50 МБ · до 10 страниц',
    textPlaceholder: 'Вставьте текст документа…', clear: 'Очистить', characters: 'символов',
    pages: 'Страницы', noPages: 'Страницы ещё не добавлены.', addPage: 'Добавить страницу',
    rotate: 'Повернуть', crop: 'Обрезать', delete: 'Удалить', moveUp: 'Выше', moveDown: 'Ниже', replace: 'Заменить', preview: 'Просмотр',
    analysisSettings: 'Настройки анализа', resultLanguage: 'Язык результата', explanationLevel: 'Уровень объяснения',
    standard: 'Стандартно', verySimple: 'Очень просто', verySimpleDesc: 'Короткие предложения и понятные действия без сложных формулировок.',
    documentType: 'Тип документа', autoDetect: 'Определить автоматически', announcement: 'Объявление', workOrder: 'Рабочее поручение', handwritten: 'Рукописная записка', other: 'Другое',
    provider: 'Способ анализа', localProvider: 'Локально в браузере', remoteProvider: 'Подключённый backend', automatic: 'Автоматически',
    localProviderDesc: 'Текст и текстовые PDF анализируются без отправки документа. Для OCR изображений подключите backend.',
    createPlan: 'Создать понятный план', draftSaved: 'Черновик сохранён', continueDraft: 'Продолжить черновик', discard: 'Удалить',
    processTitle: 'Анализируем документ', processSubtitle: 'Не закрывайте вкладку. Текущий прогресс сохраняется.',
    processRead: 'Читаем документ', processFind: 'Находим важную информацию', processVerify: 'Проверяем даты, суммы и места', processTasks: 'Создаём список действий',
    cancel: 'Отменить', backHome: 'На главную', retry: 'Повторить', openResult: 'Открыть результат',
    resultTitleFallback: 'Результат анализа', analyzed: 'Проанализировано',
    summary: 'Простое объяснение', tasks: 'Что нужно сделать', importantData: 'Важные данные', clarifications: 'Уточнения', warnings: 'Предупреждения',
    noTasks: 'Конкретные действия в документе не обнаружены.', noData: 'Отдельные даты, суммы, адреса или контакты не обнаружены.', noWarnings: 'Предупреждений нет.',
    completed: 'Выполнено', notCompleted: 'Не выполнено', priority: 'Приоритет', high: 'Высокий', medium: 'Средний', low: 'Низкий',
    dueDate: 'Срок', source: 'Источник', showSource: 'Показать в документе', confidence: 'Уверенность', confidenceHigh: 'Высокая', confidenceMedium: 'Средняя', confidenceLow: 'Низкая',
    copySummary: 'Скопировать объяснение', copyTasks: 'Скопировать задачи', copyAll: 'Скопировать всё', downloadPdf: 'Скачать PDF', addCalendar: 'Добавить в календарь', share: 'Поделиться', save: 'Сохранить', reanalyze: 'Анализировать снова',
    copied: 'Скопировано', pdfCreated: 'PDF создан', calendarCreated: 'Файл календаря создан', saved: 'Сохранено', saving: 'Сохранение…', saveFailed: 'Не удалось сохранить',
    editTask: 'Редактировать задачу', taskName: 'Название', description: 'Описание', date: 'Дата', time: 'Время', location: 'Место', reminder: 'Напоминание', saveChanges: 'Сохранить изменения',
    confirmDelete: 'Удалить анализ?', confirmDeleteText: 'Результат и локальный черновик будут удалены без возможности восстановления.',
    historyTitle: 'История анализов', historySubtitle: 'Сохранённые результаты, задачи и предупреждения.', search: 'Поиск', all: 'Все', withOpenTasks: 'С незавершёнными задачами', withWarnings: 'С предупреждениями',
    noResults: 'Ничего не найдено', rename: 'Переименовать', open: 'Открыть', loadMore: 'Показать ещё',
    settingsTitle: 'Настройки', settingsSubtitle: 'Интерфейс, анализ, уведомления, данные и установка приложения.',
    interface: 'Интерфейс', language: 'Язык интерфейса', theme: 'Тема', themeSystem: 'Системная', themeLight: 'Светлая', themeDark: 'Тёмная', textSize: 'Размер текста', reduceMotion: 'Уменьшить анимации',
    analysis: 'Анализ', defaultResultLanguage: 'Язык результата по умолчанию', defaultExplanation: 'Объяснение по умолчанию', analysisMode: 'Режим анализа', apiUrl: 'Адрес backend API', apiUrlHint: 'Например: https://api.example.com. Секретные ключи во frontend не используются.',
    notifications: 'Уведомления', allowNotifications: 'Разрешить уведомления', testNotification: 'Тест уведомления',
    data: 'Данные', exportData: 'Экспортировать данные', deleteHistory: 'Удалить всю историю', sourceDeletionInfo: 'Исходные файлы хранятся только локально, если не настроен backend.',
    pwa: 'Приложение PWA', installApp: 'Установить приложение', updateApp: 'Проверить обновление', version: 'Версия', cacheStatus: 'Offline-кеш', ready: 'Готов',
    installTitle: 'Установка Фаҳмо AI', installSubtitle: 'Приложение можно установить на телефон или компьютер.',
    installAndroid1: 'Откройте меню браузера.', installAndroid2: 'Выберите «Установить приложение».', installAndroid3: 'Подтвердите установку.',
    installIos1: 'Откройте сайт в Safari.', installIos2: 'Нажмите «Поделиться».', installIos3: 'Выберите «На экран Домой».',
    offlineTitle: 'Нет подключения', offlineText: 'Документ можно сохранить как черновик. Анализ через backend станет доступен после восстановления интернета.',
    sharedTitle: 'Сохранённый результат', sharedLocalWarning: 'Эта локальная ссылка доступна только в текущем браузере. Для публичной ссылки подключите backend.',
    publicShareTitle: 'Создать ссылку', publicShareText: 'Любой человек с публичной ссылкой сможет увидеть сохранённый результат. Исходный документ не публикуется.', disableShare: 'Отключить ссылку', disableShareText: 'После отключения сохранённая ссылка больше не будет открывать результат.', shareDisabled: 'Ссылка отключена', confirm: 'Подтвердить',
    sourcePage: 'Страница', sourceExcerpt: 'Фрагмент', confirmed: 'Подтверждено вами', close: 'Закрыть',
    errorTitle: 'Не удалось выполнить действие', genericError: 'Повторите попытку. Если проблема сохраняется, проверьте файл или подключение.',
    invalidFormat: 'Этот формат не поддерживается.', fileTooLarge: 'Файл превышает допустимый размер 50 МБ.', tooManyPages: 'Можно подготовить не более 10 страниц.', emptyText: 'Добавьте файл или вставьте текст документа.',
    unreadableDocument: 'Не удалось извлечь текст. Для изображения или сканированного PDF подключите backend OCR либо вставьте текст вручную.',
    localAnalysisNotice: 'Локальный режим извлекает только факты, которые явно присутствуют в тексте. Он не отправляет документ на внешний сервис.',
    sampleName: 'Пример: объявление о регистрации', sampleType: 'Демонстрационный документ',
    installUnavailable: 'Автоматическая установка недоступна. Используйте меню браузера.', notificationSent: 'Тестовое уведомление отправлено.',
    cropTitle: 'Обрезка страницы', cropHint: 'Перемещайте рамку и тяните маркер в правом нижнем углу.', apply: 'Применить',
    statusDraft: 'Черновик', statusProcessing: 'Обрабатывается', statusCompleted: 'Готово', statusFailed: 'Ошибка', statusCancelled: 'Отменено',
    document: 'Документ', taskCount: 'задач', warningCount: 'предупреждений',
    amount: 'Сумма', address: 'Адрес', contact: 'Контакт', link: 'Ссылка', deadline: 'Крайний срок', dateLabel: 'Дата', timeLabel: 'Время',
    sourceUnavailable: 'Координаты фрагмента отсутствуют. Показаны номер страницы и найденный текст.',
    remoteUnavailable: 'Backend API не настроен или временно недоступен. Черновик сохранён.',
    createdLocally: 'Создано локально', publicLinkRequiresBackend: 'Для ссылки, доступной другим людям, требуется backend. Сейчас создана локальная ссылка для этого браузера.',
    dataExported: 'Данные экспортированы.', historyDeleted: 'История удалена.', updateAvailable: 'Доступно обновление', updateNow: 'Обновить', later: 'Позже',
    pendingDraftTitle: 'У вас есть незавершённый документ', pendingDraftText: 'Можно продолжить с того места, где вы остановились.'
  },
  tg: {
    appName: 'Фаҳмо AI', tagline: 'Аз ҳуҷҷат — ба нақшаи фаҳмо',
    navHome: 'Асосӣ', navAnalyze: 'Таҳлили нав', navHistory: 'Таърих', navSettings: 'Танзимот', online: 'Пайваст', offline: 'Пайваст нест',
    heroDescription: 'Эълон, супориш, ёддошт ё ҳуҷҷати дигарро бор кунед. Мо маълумоти асосиро ҷудо карда, рӯйхати амалҳои фаҳморо месозем.',
    addDocument: 'Илова кардани ҳуҷҷат', tryExample: 'Санҷидан бо мисол', supported: 'Акс · Тасвир · PDF · Матн',
    flowShort: 'Кӯтоҳ ва фаҳмо', flowShortDesc: 'Мазмунро ҷудо карда, маълумоти зиёдатиро мегирем.',
    flowTasks: 'Чӣ бояд кард', flowTasksDesc: 'Маълумотро ба қадамҳои мушаххас табдил медиҳем.',
    flowData: 'Маълумоти муҳим', flowDataDesc: 'Сана, маблағ, ҷой ва тамосҳоро меёбем.', flowSource: 'Манбаъҳо', flowSourceDesc: 'Нишон медиҳем, ки маълумот аз куҷо гирифта шудааст.',
    recent: 'Таҳлилҳои охир', viewAll: 'Ҳамаро дидан', noHistoryTitle: 'Таърих ҳоло холӣ аст', noHistoryText: 'Ҳуҷҷати аввалро илова кунед ё мисоли бехатарро оғоз намоед.',
    stepAdd: 'Илова', stepReview: 'Саҳифаҳоро санҷед', stepConfigure: 'Таҳлилро танзим кунед', analyzeTitle: 'Омодасозии ҳуҷҷат', analyzeSubtitle: 'Саҳифаҳоро илова карда, тартиб ва параметрҳои натиҷаро санҷед.',
    sourceFiles: 'Файлҳо', sourceText: 'Матн', dropTitle: 'Файлро ба ин ҷо кашед', dropText: 'ё роҳи мувофиқро интихоб кунед', chooseFile: 'Интихоби файл', takePhoto: 'Акс гирифтан', pasteImage: 'Гузоштани тасвир', pasteText: 'Гузоштани матн', uploadHint: 'PDF, PNG, JPG, WEBP ё TXT · то 50 МБ · то 10 саҳифа',
    textPlaceholder: 'Матни ҳуҷҷатро гузоред…', clear: 'Пок кардан', characters: 'аломат', pages: 'Саҳифаҳо', noPages: 'Ҳоло саҳифа илова нашудааст.', addPage: 'Иловаи саҳифа', rotate: 'Гардондан', crop: 'Буридан', delete: 'Нест кардан', moveUp: 'Боло', moveDown: 'Поён', replace: 'Иваз кардан', preview: 'Пешнамоиш',
    analysisSettings: 'Танзимоти таҳлил', resultLanguage: 'Забони натиҷа', explanationLevel: 'Сатҳи шарҳ', standard: 'Одатӣ', verySimple: 'Хеле сода', verySimpleDesc: 'Ҷумлаҳои кӯтоҳ ва амалҳои фаҳмо бе ибораҳои душвор.', documentType: 'Навъи ҳуҷҷат', autoDetect: 'Худкор муайян кардан', announcement: 'Эълон', workOrder: 'Супориши корӣ', handwritten: 'Ёддошти дастнавис', other: 'Дигар', provider: 'Усули таҳлил', localProvider: 'Дар браузер', remoteProvider: 'Backend-и пайвастшуда', automatic: 'Худкор', localProviderDesc: 'Матн ва PDF-и матндор бе фиристодани ҳуҷҷат таҳлил мешавад. Барои OCR-и тасвир backend лозим аст.', createPlan: 'Сохтани нақшаи фаҳмо', draftSaved: 'Лоиҳа нигоҳ дошта шуд', continueDraft: 'Идома додан', discard: 'Нест кардан',
    processTitle: 'Ҳуҷҷатро таҳлил мекунем', processSubtitle: 'Саҳифаро набандед. Пешрафт нигоҳ дошта мешавад.', processRead: 'Ҳуҷҷатро мехонем', processFind: 'Маълумоти муҳимро меёбем', processVerify: 'Сана, маблағ ва ҷойро месанҷем', processTasks: 'Рӯйхати амалҳоро месозем', cancel: 'Бекор кардан', backHome: 'Ба асосӣ', retry: 'Такрор кардан', openResult: 'Кушодани натиҷа',
    resultTitleFallback: 'Натиҷаи таҳлил', analyzed: 'Таҳлил шуд', summary: 'Шарҳи сода', tasks: 'Чӣ бояд кард', importantData: 'Маълумоти муҳим', clarifications: 'Саволҳои дақиқкунанда', warnings: 'Огоҳӣ', noTasks: 'Дар ҳуҷҷат амали мушаххас ёфт нашуд.', noData: 'Сана, маблағ, суроға ё тамоси ҷудогона ёфт нашуд.', noWarnings: 'Огоҳӣ нест.', completed: 'Иҷро шуд', notCompleted: 'Иҷро нашуд', priority: 'Афзалият', high: 'Баланд', medium: 'Миёна', low: 'Паст', dueDate: 'Муҳлат', source: 'Манбаъ', showSource: 'Дар ҳуҷҷат нишон додан', confidence: 'Эътимод', confidenceHigh: 'Баланд', confidenceMedium: 'Миёна', confidenceLow: 'Паст',
    copySummary: 'Нусхаи шарҳ', copyTasks: 'Нусхаи вазифаҳо', copyAll: 'Нусхаи ҳама', downloadPdf: 'Боргирии PDF', addCalendar: 'Илова ба тақвим', share: 'Мубодила', save: 'Нигоҳ доштан', reanalyze: 'Аз нав таҳлил кардан', copied: 'Нусха шуд', pdfCreated: 'PDF сохта шуд', calendarCreated: 'Файли тақвим сохта шуд', saved: 'Нигоҳ дошта шуд', saving: 'Нигоҳдорӣ…', saveFailed: 'Нигоҳ дошта нашуд',
    editTask: 'Таҳрири вазифа', taskName: 'Ном', description: 'Тавсиф', date: 'Сана', time: 'Вақт', location: 'Ҷой', reminder: 'Ёдрас', saveChanges: 'Нигоҳ доштани тағйирот', confirmDelete: 'Таҳлил нест шавад?', confirmDeleteText: 'Натиҷа ва лоиҳаи маҳаллӣ бебозгашт нест мешаванд.',
    historyTitle: 'Таърихи таҳлилҳо', historySubtitle: 'Натиҷаҳо, вазифаҳо ва огоҳиҳои нигоҳдошташуда.', search: 'Ҷустуҷӯ', all: 'Ҳама', withOpenTasks: 'Бо вазифаҳои анҷомнашуда', withWarnings: 'Бо огоҳӣ', noResults: 'Натиҷа нест', rename: 'Иваз кардани ном', open: 'Кушодан', loadMore: 'Бештар нишон додан',
    settingsTitle: 'Танзимот', settingsSubtitle: 'Интерфейс, таҳлил, огоҳӣ, маълумот ва насби барнома.', interface: 'Интерфейс', language: 'Забони интерфейс', theme: 'Мавзӯъ', themeSystem: 'Системавӣ', themeLight: 'Равшан', themeDark: 'Торик', textSize: 'Андозаи матн', reduceMotion: 'Кам кардани аниматсия', analysis: 'Таҳлил', defaultResultLanguage: 'Забони натиҷаи пешфарз', defaultExplanation: 'Шарҳи пешфарз', analysisMode: 'Режими таҳлил', apiUrl: 'Суроғаи backend API', apiUrlHint: 'Мисол: https://api.example.com. Калидҳои махфӣ дар frontend нигоҳ дошта намешаванд.', notifications: 'Огоҳиномаҳо', allowNotifications: 'Иҷозаи огоҳинома', testNotification: 'Огоҳии санҷишӣ', data: 'Маълумот', exportData: 'Содир кардани маълумот', deleteHistory: 'Нест кардани тамоми таърих', sourceDeletionInfo: 'Агар backend танзим нашуда бошад, файлҳои аслӣ танҳо маҳаллӣ нигоҳ дошта мешаванд.', pwa: 'Барномаи PWA', installApp: 'Насби барнома', updateApp: 'Санҷиши навсозӣ', version: 'Версия', cacheStatus: 'Кэши offline', ready: 'Омода',
    installTitle: 'Насби Фаҳмо AI', installSubtitle: 'Барномаро дар телефон ё компютер насб кардан мумкин аст.', installAndroid1: 'Менюи браузерро кушоед.', installAndroid2: '«Насби барнома»-ро интихоб кунед.', installAndroid3: 'Насбро тасдиқ кунед.', installIos1: 'Сайтро дар Safari кушоед.', installIos2: '«Мубодила»-ро пахш кунед.', installIos3: '«Ба экрани асосӣ»-ро интихоб кунед.',
    confirmed: 'Аз ҷониби шумо тасдиқ шуд', offlineTitle: 'Пайваст нест', offlineText: 'Ҳуҷҷатро ҳамчун лоиҳа нигоҳ доштан мумкин аст. Таҳлил тавассути backend баъди барқарор шудани интернет дастрас мешавад.', sharedTitle: 'Натиҷаи нигоҳдошташуда', sharedLocalWarning: 'Ин пайванди маҳаллӣ танҳо дар ҳамин браузер дастрас аст. Барои пайванди умумӣ backend пайваст кунед.', publicShareTitle: 'Сохтани пайванд', publicShareText: 'Ҳар касе, ки пайванди умумиро дорад, натиҷаро мебинад. Ҳуҷҷати аслӣ нашр намешавад.', disableShare: 'Хомӯш кардани пайванд', disableShareText: 'Пас аз хомӯш кардан пайванди нигоҳдошташуда дигар натиҷаро намекушояд.', shareDisabled: 'Пайванд хомӯш шуд', confirm: 'Тасдиқ', sourcePage: 'Саҳифа', sourceExcerpt: 'Порча', close: 'Пӯшидан',
    errorTitle: 'Амал иҷро нашуд', genericError: 'Аз нав кӯшиш кунед. Агар мушкил монад, файл ё пайвастиро санҷед.', invalidFormat: 'Ин формат дастгирӣ намешавад.', fileTooLarge: 'Ҳаҷми файл аз 50 МБ зиёд аст.', tooManyPages: 'На бештар аз 10 саҳифа мумкин аст.', emptyText: 'Файл илова кунед ё матни ҳуҷҷатро гузоред.', unreadableDocument: 'Матн гирифта нашуд. Барои тасвир ё PDF-и сканшуда backend OCR пайваст кунед ё матнро дастӣ гузоред.', localAnalysisNotice: 'Режими маҳаллӣ танҳо далелҳои ошкоро дар матнро ҷудо мекунад ва ҳуҷҷатро ба сервиси беруна намефиристад.', sampleName: 'Мисол: эълони бақайдгирӣ', sampleType: 'Ҳуҷҷати намоишӣ', installUnavailable: 'Насби худкор дастрас нест. Менюи браузерро истифода баред.', notificationSent: 'Огоҳии санҷишӣ фиристода шуд.', cropTitle: 'Буридани саҳифа', cropHint: 'Чорчӯбаро ҳаракат диҳед ва нишонгари поёни ростро кашед.', apply: 'Татбиқ',
    statusDraft: 'Лоиҳа', statusProcessing: 'Коркард', statusCompleted: 'Омода', statusFailed: 'Хато', statusCancelled: 'Бекор', document: 'Ҳуҷҷат', taskCount: 'вазифа', warningCount: 'огоҳӣ', amount: 'Маблағ', address: 'Суроға', contact: 'Тамос', link: 'Пайванд', deadline: 'Муҳлати охир', dateLabel: 'Сана', timeLabel: 'Вақт', sourceUnavailable: 'Координатаи порча мавҷуд нест. Рақами саҳифа ва матни ёфтшуда нишон дода шудааст.', remoteUnavailable: 'Backend API танзим нашудааст ё дастрас нест. Лоиҳа нигоҳ дошта шуд.', createdLocally: 'Маҳаллӣ сохта шуд', publicLinkRequiresBackend: 'Барои пайванди дастрас ба дигарон backend лозим аст. Ҳоло пайванди маҳаллӣ барои ҳамин браузер сохта шуд.', dataExported: 'Маълумот содир шуд.', historyDeleted: 'Таърих нест шуд.', updateAvailable: 'Навсозӣ дастрас аст', updateNow: 'Навсозӣ', later: 'Баъдтар', pendingDraftTitle: 'Ҳуҷҷати нотамом доред', pendingDraftText: 'Аз ҷои қатъшуда идома дода метавонед.'
  },
  en: {
    appName: 'Fahmo AI', tagline: 'From document to a clear plan', navHome: 'Home', navAnalyze: 'New analysis', navHistory: 'History', navSettings: 'Settings', online: 'Online', offline: 'Offline',
    heroDescription: 'Upload an announcement, assignment, note, or another document. We will extract the essentials and create a clear action list.', addDocument: 'Add document', tryExample: 'Try an example', supported: 'Photo · Images · PDF · Text', flowShort: 'Clear summary', flowShortDesc: 'Extracts the essentials and removes noise.', flowTasks: 'What to do', flowTasksDesc: 'Turns information into concrete steps.', flowData: 'Important data', flowDataDesc: 'Finds dates, amounts, places, and contacts.', flowSource: 'Sources', flowSourceDesc: 'Shows where each fact came from.', recent: 'Recent analyses', viewAll: 'View all', noHistoryTitle: 'History is empty', noHistoryText: 'Add your first document or run the safe example to see the full flow.',
    stepAdd: 'Add', stepReview: 'Review pages', stepConfigure: 'Configure', analyzeTitle: 'Prepare document', analyzeSubtitle: 'Add pages, verify their order, and select result settings.', sourceFiles: 'Files', sourceText: 'Text', dropTitle: 'Drop a file here', dropText: 'or choose another way to add it', chooseFile: 'Choose file', takePhoto: 'Take photo', pasteImage: 'Paste image', pasteText: 'Paste text', uploadHint: 'PDF, PNG, JPG, WEBP, or TXT · up to 50 MB · up to 10 pages', textPlaceholder: 'Paste document text…', clear: 'Clear', characters: 'characters', pages: 'Pages', noPages: 'No pages added yet.', addPage: 'Add page', rotate: 'Rotate', crop: 'Crop', delete: 'Delete', moveUp: 'Move up', moveDown: 'Move down', replace: 'Replace', preview: 'Preview',
    analysisSettings: 'Analysis settings', resultLanguage: 'Result language', explanationLevel: 'Explanation level', standard: 'Standard', verySimple: 'Very simple', verySimpleDesc: 'Short sentences and clear actions without complex wording.', documentType: 'Document type', autoDetect: 'Detect automatically', announcement: 'Announcement', workOrder: 'Work assignment', handwritten: 'Handwritten note', other: 'Other', provider: 'Analysis method', localProvider: 'Locally in browser', remoteProvider: 'Connected backend', automatic: 'Automatic', localProviderDesc: 'Text and text PDFs are analyzed without uploading the document. Connect a backend for image OCR.', createPlan: 'Create clear plan', draftSaved: 'Draft saved', continueDraft: 'Continue', discard: 'Delete',
    processTitle: 'Analyzing document', processSubtitle: 'Keep this tab open. Current progress is saved.', processRead: 'Reading the document', processFind: 'Finding important information', processVerify: 'Checking dates, amounts, and places', processTasks: 'Creating the action list', cancel: 'Cancel', backHome: 'Back home', retry: 'Retry', openResult: 'Open result', resultTitleFallback: 'Analysis result', analyzed: 'Analyzed', summary: 'Simple explanation', tasks: 'What to do', importantData: 'Important data', clarifications: 'Clarifications', warnings: 'Warnings', noTasks: 'No explicit actions were found in the document.', noData: 'No separate dates, amounts, addresses, or contacts were found.', noWarnings: 'No warnings.', completed: 'Completed', notCompleted: 'Not completed', priority: 'Priority', high: 'High', medium: 'Medium', low: 'Low', dueDate: 'Due date', source: 'Source', showSource: 'Show in document', confidence: 'Confidence', confidenceHigh: 'High', confidenceMedium: 'Medium', confidenceLow: 'Low',
    copySummary: 'Copy explanation', copyTasks: 'Copy tasks', copyAll: 'Copy all', downloadPdf: 'Download PDF', addCalendar: 'Add to calendar', share: 'Share', save: 'Save', reanalyze: 'Analyze again', copied: 'Copied', pdfCreated: 'PDF created', calendarCreated: 'Calendar file created', saved: 'Saved', saving: 'Saving…', saveFailed: 'Could not save', editTask: 'Edit task', taskName: 'Title', description: 'Description', date: 'Date', time: 'Time', location: 'Location', reminder: 'Reminder', saveChanges: 'Save changes', confirmDelete: 'Delete analysis?', confirmDeleteText: 'The result and local draft will be permanently deleted.',
    historyTitle: 'Analysis history', historySubtitle: 'Saved results, tasks, and warnings.', search: 'Search', all: 'All', withOpenTasks: 'With open tasks', withWarnings: 'With warnings', noResults: 'Nothing found', rename: 'Rename', open: 'Open', loadMore: 'Show more', settingsTitle: 'Settings', settingsSubtitle: 'Interface, analysis, notifications, data, and app installation.', interface: 'Interface', language: 'Interface language', theme: 'Theme', themeSystem: 'System', themeLight: 'Light', themeDark: 'Dark', textSize: 'Text size', reduceMotion: 'Reduce motion', analysis: 'Analysis', defaultResultLanguage: 'Default result language', defaultExplanation: 'Default explanation', analysisMode: 'Analysis mode', apiUrl: 'Backend API URL', apiUrlHint: 'Example: https://api.example.com. Secret keys are never stored in the frontend.', notifications: 'Notifications', allowNotifications: 'Allow notifications', testNotification: 'Test notification', data: 'Data', exportData: 'Export data', deleteHistory: 'Delete all history', sourceDeletionInfo: 'Original files remain local unless a backend is configured.', pwa: 'PWA app', installApp: 'Install app', updateApp: 'Check for update', version: 'Version', cacheStatus: 'Offline cache', ready: 'Ready',
    installTitle: 'Install Fahmo AI', installSubtitle: 'Install the app on your phone or computer.', installAndroid1: 'Open the browser menu.', installAndroid2: 'Choose “Install app”.', installAndroid3: 'Confirm the installation.', installIos1: 'Open the site in Safari.', installIos2: 'Tap Share.', installIos3: 'Choose “Add to Home Screen”.', confirmed: 'Confirmed by you', offlineTitle: 'No connection', offlineText: 'The document can be saved as a draft. Backend analysis will be available after the connection is restored.', sharedTitle: 'Saved result', sharedLocalWarning: 'This local link is available only in the current browser. Connect a backend for a public link.', publicShareTitle: 'Create link', publicShareText: 'Anyone with the public link can view the saved result. The original document is not published.', disableShare: 'Disable link', disableShareText: 'After disabling, the saved link will no longer open this result.', shareDisabled: 'Link disabled', confirm: 'Confirm', sourcePage: 'Page', sourceExcerpt: 'Excerpt', close: 'Close', errorTitle: 'Action failed', genericError: 'Try again. If the problem remains, check the file or connection.', invalidFormat: 'This format is not supported.', fileTooLarge: 'The file exceeds the 50 MB limit.', tooManyPages: 'You can prepare up to 10 pages.', emptyText: 'Add a file or paste document text.', unreadableDocument: 'Text could not be extracted. Connect OCR backend for an image or scanned PDF, or paste text manually.', localAnalysisNotice: 'Local mode extracts only facts explicitly present in the text and does not send the document to an external service.', sampleName: 'Example: registration announcement', sampleType: 'Demo document', installUnavailable: 'Automatic installation is unavailable. Use the browser menu.', notificationSent: 'Test notification sent.', cropTitle: 'Crop page', cropHint: 'Move the frame and drag the bottom-right handle.', apply: 'Apply',
    statusDraft: 'Draft', statusProcessing: 'Processing', statusCompleted: 'Ready', statusFailed: 'Error', statusCancelled: 'Cancelled', document: 'Document', taskCount: 'tasks', warningCount: 'warnings', amount: 'Amount', address: 'Address', contact: 'Contact', link: 'Link', deadline: 'Deadline', dateLabel: 'Date', timeLabel: 'Time', sourceUnavailable: 'No fragment coordinates were provided. The page number and extracted text are shown.', remoteUnavailable: 'Backend API is not configured or unavailable. The draft was saved.', createdLocally: 'Created locally', publicLinkRequiresBackend: 'A backend is required for a link accessible to other people. A local link for this browser was created instead.', dataExported: 'Data exported.', historyDeleted: 'History deleted.', updateAvailable: 'Update available', updateNow: 'Update', later: 'Later', pendingDraftTitle: 'You have an unfinished document', pendingDraftText: 'Continue from where you stopped.'
  }
};

let currentLanguage = localStorage.getItem('fahmo:language') || 'ru';
if (!dictionaries[currentLanguage]) currentLanguage = 'ru';

export function getLanguage() { return currentLanguage; }
export function setLanguage(language) {
  if (!dictionaries[language]) return;
  currentLanguage = language;
  localStorage.setItem('fahmo:language', language);
  document.documentElement.lang = language === 'tg' ? 'tg' : language;
  window.dispatchEvent(new CustomEvent('fahmo:language-change', { detail: language }));
}
export function t(key, variables = {}) {
  const template = dictionaries[currentLanguage]?.[key] ?? dictionaries.ru[key] ?? key;
  return Object.entries(variables).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template);
}
export function dictionary(language = currentLanguage) { return dictionaries[language] ?? dictionaries.ru; }
export const supportedLanguages = ['ru', 'tg', 'en'];
